-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 09:13:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foodsharing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foodsharing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foodsharing` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `foodsharing` ;

-- -----------------------------------------------------
-- Table `foodsharing`.`foodsharing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodsharing`.`foodsharing` (
  `idfood` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descr` VARCHAR(225) NOT NULL,
  `metro` VARCHAR(45) NOT NULL,
  `adres` VARCHAR(90) NOT NULL,
  `numb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfood`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
